
discount_func:
  expo:
    x0: [.5] #delta
    bound: [[.001,100]]
  expo2:
    x0: [.5,.5,.5] #delta1,delta2,d_weight
    bound: [[.001,1],[.001,1],[.001,1]]
  hb:
    x0: [1] #k
    bound: [[.001,100]]
  hb2:
    x0: [1,1] #k,a
    bound: [[.001,100],[.001,100]]
  hbmd:
    x0: [1] #b
    bound: [[.001,100]]
  quasihb:
    x0: [.5,.5] #beta,delta
    bound: [[.001,1],[.001,1]]
  quasihb_fc:
    x0: [.5,.5,1] #beta,delta,c
    bound: [[.001,1],[.001,1],[.001,100]]
  hce:
    x0: [.5,2] #delta,m
    bound: [[.001,1],[1.001,100]]
  attention:
    x0: [.5,1] #delta,lambd
    bound: [[.001,1],[.001,100]]
  attention_uni:
    x0: [1] #lambd
    bound: [[.001,100]]
utility_func:
  power:
    x0: [.5]
    bound: [[.001,100]]
  cara:
    x0: [1]
    bound: [[.001,100]]
  power2:
    x0: [1,.5]
    bound: [[.001,100],[.001,1]]
  log:
    x0: [1,.5]
    bound: [[.001,100],[.001,100]]
choice_prob:
  temper:
    x0: [5]
    bound: [[.001,100]]