---
title: "Progress Report for Annual Review 22/23 - v2"
author: "Zark Zijian Wang"
date: "`r format(Sys.time(), '%B %d, %Y')`"
bibliography: reference.bib
biblio-style: apalike
header-includes: 
  \usepackage{setspace}
  \usepackage{amsmath}
  \usepackage{array}
  \usepackage{caption}
  \usepackage{longtable}
  \usepackage{booktabs}
  \usepackage{enumitem}
  \renewcommand{\arraystretch}{1}
  \captionsetup[table]{skip=5pt}
  \setstretch{1.5} 
fontsize: 12pt
geometry: margin=1in
editor_options: 
  markdown: 
    wrap: 72
output:
  #word_document:
    #number_sections: true
  pdf_document:
    number_sections: true
    citation_package: natbib
    keep_tex: true
  html_document:
    toc: true
    number_sections: true
---

# Introduction

In this document, I introduce three pieces of work.

The first is a model I term "attentional discounted utility". I leverage
attentional mechanism to explain the anomalies in intertemporal choice.
The model is developed based on expected discounted utility framework.

The second is an experimental test on whether (and how) attentional
mechanism can influence intertemporal choice.

The third is an experiment aiming to test how people valuate risky
outcomes and efforts. One prominent application of the findings from
this experiment is that to help us validate a key hypothesis in rational
inattention theories. I have designed the experimental program.

# Attentional Discounted Utility

## The Model

Expected discounted utility framework has been widely used in behavioral
and economic research. Given a sequence of rewards
$X_T=[x_0,x_1,...,x_T]$, which yields reward $x_t$ in time period
$t$.[^1] For any $t \in \{0,1,...,T\}$, the reward level $x_t$ is a
random variable defined on $\mathbb{R}_{\geq 0}$. Then, the expected
discounted utility of $X_T$ is calculated by$$
EDU(X_T)= \mathbb{E}\left[\sum_{t=0}^T d_t u(x_t)\right]
$$where $d_t$ is the discounting factor of time period $t$, $u(.)$
denote the decision maker's instantaneous utility function, where $u'>0$
and $u''<0$. The time length of this sequence, denoted by $T$, is
finite.

[^1]: I use uppercase letters to represent a sequence and lowercase
    letters to represent each element within the sequence.

I develop a model that incorporates attentional mechanism into the
valuation of a reward sequence. I term the model as *attentional
discounted utility with Shannon cost function* (ADUS). It remains the
expected discounted utility framework, but modifies the discounting
factor $d_t$ to an attention weight $w_t$, where

```{=tex}
\begin{equation}\tag{1}\label{eq:wt}
w_t = \frac{d_t e^{u(x_t)/\lambda}}{\sum_{\tau=0}^T d_\tau e^{u(x_\tau)/\lambda}}
\end{equation}
```
Equation (\ref{eq:wt}) indicates three properties of attention. First,
the sum of all $w_t$ is 1, which indicates the decision maker has
limited attention to allocate for each period. Second, $w_t$ is
increasing in $x_t$, which indicates the decision maker is motivated to
allocate more attention to periods with larger rewards. This is in line
with the substantial evidence that suggests people tend to attend more
to pleasant information and avoid unpleasant information (e.g. ostrich
effect). Third, $d_t$ serves as the original attention weight assigned
to each period, and $w_t$ seems "anchored" in it. This indicates the
attention adjustment process is costly. $\lambda$ is a parameter that
measures the cost of attention adjustment.

I provide two rationales for Equation (\ref{eq:wt}). The first is based
on rational inattention theories. The second is an axiomatic
characaterization. I present the first here and discuss the second in
Section \ref{axiom}.

The necessary notations and definitions are described as follows. Let
$S_T=[s_0,s_1,...,s_T]$ be a potential realization of $X_T$, and
$\mathcal{S}(X_T)$ be the support of $X_T$, i.e. the smallest set
containing any potentially realized sequence $S_T$, where
$\mathcal{S}(X_T)\subseteq \mathbb{R}_{\geq 0}^{T+1}$. In each $S_T$,
the attention weight assigned to period $t$ is decided by a weight
function $w(s_t)$. I follow Noor and Takeoka [-@noor_optimal_2022;
-@noor_constrained_2023] to define the process that generates $w(s_t)$
as *constrained optimal discounting*. The key assumption of constrained
optimal discounting process is that, when evaluating a reward sequence,
the decision maker tends to re-allocate attention weights across the
time periods, in order to maximize the anticipatory utility that she can
obtain from the sequence. However, doing this will trigger a cognitive
cost. She needs to balance the benefit of focusing on periods that
contain larger rewards and the cognitive cost of shifting attention. The
formal definition is given by Definition 1.

**Definition 1**: Let $W$ be the smallest set containing all possible
weight functions. Given a stochastic reward sequence $X_T$, the
following optimization problem is called the *constrained optimal
discounting* problem for $X_T$:$$ 
\begin{aligned}
\max_{w\in W}  \quad & \sum_{S_T\in \mathcal{S}(X_T)}\sum_{t=0}^T w(s_t)u(s_t) - C(w) \\
s.t. \quad &  \sum_{S_T\in \mathcal{S}}\sum_{t=0}^T w(s_t)=m \\
& w(s_t)\geq 0, \forall t\in\{0,1,…,T\} \\
\end{aligned}
$$where $m$ is a constant, $C:[0,m]^{T+1}\rightarrow \mathbb{R}_{>0}$ is
called *information cost* function, $\partial C/\partial w(s_t)>0$ and
$\partial^2 C/\partial w(s_t)^2>0$. That is, the cost of information is
increasing and convex in $w(s_t)$.

The cognitive cost $C(.)$ is also called information cost function,
because it depends on which piece of reward information that the
decision maker wants to focus on. A well-known specification of
information cost function is the Shannon cost function, proposed by
@matejka_rational_2015. The Shannon cost function was originally used to
justify the multinominal logit model in discrete choice analysis, and so
far has been topical in rational inattention literature. To construct
this style of information cost function, @matejka_rational_2015
introduce three assumptions. The first is that the sum of all weights
$m\equiv1$. The second assumption is, before acquiring any information,
the decision maker establishes an initial allocation of weights for
different attributes, which remains invariant over states. The weights
are then updated in a manner consistent with Bayes rule. Suppose the
initial weight assigned to period $t$ is $d_t$, then
$d_t=\sum_{S_T\in \mathcal{S}(X_T)} w(s_t)$. The third assumption is,
the cost of information is linear to the information gains, measured by
Shannon mutual information. That
is,$$ C(w)= \lambda \sum_{S_T\in \mathcal{S}(X_T)}\sum_{t=0}^T w(s_t) \log\left(\frac{w_t(S_T)}{d_t}\right) $$where
$\lambda$ is a parameter denoting unit cost of information
($\lambda>0$). With the Shannon cost function, the constrained optimal
discounting problem can be easily solved by Lagrangian method, and the
solution is the same as Equation (\ref{eq:wt}).

## Implications in Intertemporal Choice

Here I document six implications of the ADUS model in intertemporal
choice. Each of them can be precisely proved.

1.  The model is consistent with "hidden zero effect".

2.  The requirement of magnitude effect on curvature of utility function
    can be relaxed under ADUS.

3.  The model specifies a novel condition for common difference effect.

4.  ADUS suggests that the discount function may be concave for the near
    future and convex for the far future.

5.  The model offers an alternative account for S-shaped value function.

## Axiomatic Characterization \label{axiom}

## The Role of Attention Updating in Inconsistent Planning

## Empirical Analysis

# Limited and Motivated Attention over Sequential Outcomes

# Valuation of Risk and Effort

# Time Schedule

# Reply to Comments
